### ISSUE TITLE
not work under internet circumstances

### ISSUE THREAD

**Issue by cnssl** [cody0704/xdp-examples#3]
use the eth interface lo works fine.

but when i use eth interface ,such as enp2s0f0, which has internet ip address, such as 123.124.124.123, does not work

server side :
go run main.go -linkname enp2s0f0 -port 6000

client side : 
nc -vu 123.124.124.123 6000

anything wrong?

**Comment by cody0704** [comment]
Let's make sure it's not a network environment issue.

There are two scenarios that need to be checked:

1. Check if the internal IP is functioning properly, such as 192.168.123.123.

```bash
# Server
go run main.go -linkname enp2s0f0 -port 6000

# Client
nc -vu 192.168.123.123 6000
```

2. Ensure that both the firewall and router are properly configured.

```bash
# Server
nc -lu 123.124.124.123 6000

# Client
nc -vu 123.124.124.123 6000
```

**Comment by cnssl** [comment]
there is no issue about firewall between two ends.

under this circumstance:
`go run main.go -linkname enp2s0f0 -port 6000`
the client can connect to the server, but server side received nothing .
server:
![s1](https://github.com/cody0704/xdp-examples/assets/16932709/afab1f8b-8090-4f5d-9ecb-0748e2ab919b)
client:
![c1](https://github.com/cody0704/xdp-examples/assets/16932709/610bf72c-634c-4f27-8abb-7792fdb8f8e4)

while replace the server side with nc
`nc -lu 123.124.124.123 6000`
erverything works fine.

server:
![s2](https://github.com/cody0704/xdp-examples/assets/16932709/20140ea3-c776-4400-838c-257748aa7574)
client:
![c2](https://github.com/cody0704/xdp-examples/assets/16932709/056f9175-8375-4af3-a81a-037d849b475d)

this below is my eth interface configuration.

![network](https://github.com/cody0704/xdp-examples/assets/16932709/a9d927cc-b4f5-4b73-b5f4-26d0359b514e)

**Comment by cody0704** [comment]
Let's make sure the versions are consistent.

```bash
git rev-parse HEAD
```

Then please provide me with some relevant information, and I will proceed with the reproduction to identify the issue.

```bash
# Kernel
uname -a

# OS
cat /etc/*release | grep DISTRIB

# Interface info
lspci | grep -i Ethernet
```

**Comment by cnssl** [comment]
$: git rev-parse HEAD
`d4e770f34fa532be338fb497742816a805b25074`

$: uname -a
`Linux proxy 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

$:cat /etc/*release | grep DISTRIB
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

$: lspci | grep -i Ethernet
```
02:00.0 Ethernet controller: Intel Corporation 82576 Gigabit Network Connection (rev 01)
02:00.1 Ethernet controller: Intel Corporation 82576 Gigabit Network Connection (rev 01)
```

snapshot:

![WX20230524-112456@2x](https://github.com/cody0704/xdp-examples/assets/16932709/005e2c9b-27de-4e51-8d54-ef3ef7065993)

**Comment by cody0704** [comment]
There is some foundational knowledge about XDP that has not been mentioned in the project. You need to verify the information about the network card.

You need to ensure that your information can be sent to a queue that has XDP (eXpress Data Path) capability.

```bash
ethtool -l enp2s0f0
```

* my env



```
root@lab:~# ethtool -l ens19
Channel parameters for ens19:
Pre-set maximums:
RX:		n/a
TX:		n/a
Other:		n/a
Combined:	1
Current hardware settings:
RX:		n/a
TX:		n/a
Other:		n/a
Combined:	1
```

If rx or combined is not equal to 1, it needs to be configured as 1.

```bash
# set rx
ethtool -L enp2s0f0 rx 1

# set combined
ethtool -L enp2s0f0 combined 1
```

In reality, there are three parameters: linkname, prot, and queueid. However, the example only includes linkname and prot, while queueid defaults to 0. In the experiment, the network card needs to be configured with a single RX queue to ensure that packets pass through the XDP program.

**Comment by cnssl** [comment]
thank you very much !

**Comment by cody0704** [comment]
Is it working properly now?

**Comment by cnssl** [comment]
yeah, it works all right.
